import argparse
from pathlib import Path
from typing import List

from cccv import ConfigType, ModelType

projectPATH = Path(__file__).resolve().parent.parent.absolute()


def gen_ts(output: Path) -> None:
    """
    Automatically generate the list of pretrained models for TypeScript, which is used in the frontend.

    ---

    /**
     * @description: all SR models provided by ccrestoration
     */
    export const modelOptions: any[] = [
      { label: 'RealESRGAN_RealESRGAN_x2plus_2x', value: 'RealESRGAN_RealESRGAN_x2plus_2x.pth' },
      {
        label: 'RealESRGAN_AnimeJaNai_HD_V3_Compact_2x',
        value: 'RealESRGAN_AnimeJaNai_HD_V3_Compact_2x.pth'
      }
    ]

    """

    config_list: List[ConfigType] = []

    # add new sr models here
    all_sr_models = [
        ModelType.RealESRGAN,
        ModelType.DAT,
        ModelType.HAT,
        ModelType.RealCUGAN,
        ModelType.EDSR,
        ModelType.SwinIR,
        ModelType.SCUNet,
        ModelType.SRCNN,
    ]

    for m in all_sr_models:
        for cfg in ConfigType:
            if cfg.startswith(m):
                config_list.append(cfg)  # type: ignore

    print(config_list)

    # Generate the checked-in frontend source from the Python model registry.
    output.parent.mkdir(parents=True, exist_ok=True)

    with open(output, "w", encoding="utf-8") as f:
        f.write("/* prettier-ignore */\n")
        f.write("/* tslint:disable */\n")
        f.write("/* This file is automatically generated by Final2x-core */\n")
        f.write("/* Do not modify this file manually */\n")
        f.write("// -----------------------------------------------------------------------------\n\n")

        f.write("/**\n * @description: all SR models provided by ccrestoration\n */\n")
        f.write("export const modelOptions: any[] = [\n")
        for cfg in config_list:
            f.write(f"  {{ label: '{cfg.name}', value: '{cfg.value}' }},\n")
        f.write("]\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate Final2x model options for the frontend")
    parser.add_argument(
        "--output",
        type=Path,
        default=projectPATH.parent.parent / "src" / "renderer" / "src" / "utils" / "modelOptions.ts",
    )
    gen_ts(parser.parse_args().output.resolve())
