name: CI-test

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - LICENSE
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - LICENSE
  workflow_dispatch:

permissions:
  contents: read

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint:frontend

      - name: Typecheck
        run: pnpm run typecheck

      - name: Test
        run: pnpm run test
